### ISSUE TITLE
DateString 변환 Extension 만들기

### ISSUE THREAD

**Issue by szzang-kr** [mash-up-kr/GGiriGGiri-iOS#125]
## 문제사항
- String 형태로 전달되는 (2022-09-07T23:59:59) 값을 앱에서 사용하기 편하게 `20220907` 혹은 `23:59:59`의 String으로 나타내는 객체가 필요할듯
## 해결방법 
 - String Extension에서 StringDate에서 필요한 케이스의 문자열을 return하도록 하는 method 작성하기
## 해야할 기능
- [x] YYYYMMDD / HH:mm:SS 반환 여부 체크

**Comment by kimkyunghun3** [comment]
![스크린샷 2022-08-11 오후 3 09 53](https://user-images.githubusercontent.com/52434820/184073812-455d4631-98ac-4f03-80f5-16c42e932986.png)

String -> Date
String -> String
String -> String
가능하게 했습니다~
