### ISSUE TITLE
이미지 로드 라이브러리 추가하기

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/GGiriGGiri-iOS#23]
## 문제사항
이미지 로드 라이브러리가 필요한 상황

## 해야할 기능
- [x] 이미지 로드 라이브러리 추가하기

**Comment by szzang-kr** [comment]
https://www.ralfebert.com/ios/examples/async-image-loading/

주로 사용되는 이미지 로드 라이브러리인  Kingfisher 와 SDWebImage에 대한 비교글입니다. 참고하시면 좋을 것 같습니다.

**Comment by szzang-kr** [comment]
프로젝트에 이미 추가해두었네요 죄송합니다 😭
